name: Infrastructure Deployment

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs:
  tfplan:
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: a310c866-0583-4c6d-9a39-ef9104ed48a9
          tenant-id: d7fc8fb2-8d8f-48ae-88e0-1cfdba2a7fbf
          subscription-id: 9eb6dd3b-7d3d-4d3a-82fa-3747ca6f588e
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Initialize Terraform
        run: terraform validate

      - name: Initialize Terraform
        run: terraform plan
