name: Infrastructure Deployment

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec with SARIF output
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          working_directory: .
          sarif_file: tfsec.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
          
  tfplan:
    needs: tfsec
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="dev.terraform.tfvars"
        
  tfapply:
    runs-on: ubuntu-latest
    needs: tfplan
    environment:
      name: dev
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        
      - name: Deploy infrastructure
        run: terraform apply -var-file="dev.terraform.tfvars" -auto-approve
        
          
    
